# Generated by Django 4.2.4 on 2023-08-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='address_2',
        ),
    ]
