# Generated by Django 4.2.4 on 2023-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailnewsletter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnewsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailnewsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
