# Generated by Django 4.2.4 on 2023-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address_line_1_order_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
